sudo: false

language: node_js

matrix:
  fast_finish: true
  include:
    - node_js: "9"
      env: TASK=unit
    - node_js: "8"
      env: TASK=unit
    - node_js: "6"
      env: TASK=coveralls
    - node_js: "4"
      env: TASK=unit

cache:
  directories:
  - node_modules

script:
  - make ${TASK}
